# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFormularion():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_formularion(self):
    self.driver.get("http://localhost/formulario-/")
    self.driver.set_window_size(1050, 700)
    self.driver.find_element(By.ID, "nombre").click()
    self.driver.find_element(By.ID, "apellido").click()
    self.driver.find_element(By.ID, "apellido").send_keys("alonso")
    self.driver.find_element(By.ID, "dni").click()
    self.driver.find_element(By.ID, "dni").send_keys("32945123")
    self.driver.find_element(By.ID, "fecha").click()
    self.driver.find_element(By.ID, "fecha").click()
    self.driver.find_element(By.ID, "fecha").send_keys("2003-07-17")
    self.driver.find_element(By.ID, "correo").click()
    self.driver.find_element(By.ID, "correo").send_keys("lolo@hotmail.com")
    self.driver.find_element(By.ID, "pass").click()
    self.driver.find_element(By.ID, "pass").send_keys("creton32")
    self.driver.find_element(By.ID, "reset").click()
    self.driver.find_element(By.ID, "reset").send_keys("creton32")
    self.driver.find_element(By.ID, "funka").click()
    self.driver.find_element(By.ID, "nombre").click()
    self.driver.find_element(By.ID, "nombre").send_keys("fernando")
    self.driver.find_element(By.ID, "funka").click()
    self.driver.close()
  
# time.sleep